trigger: none

pr:
  branches:
    include:
      - main
  paths:
    include:
      - GloboTicket.Gateway.Ocelot/**
      - k8s/aks/aks-gateway-ocelot.yaml
      - k8s/aks/aks-gateway-ocelot-service.yaml
      - k8s/aks/aks-config-gateway-ocelot.yaml

pool:
  name: Default

variables:
  buildConfiguration: Release

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore GloboTicket.Gateway.Ocelot/GloboTicket.Gateway.Ocelot.csproj
  displayName: Restore

- script: dotnet build GloboTicket.Gateway.Ocelot/GloboTicket.Gateway.Ocelot.csproj --no-restore -c $(buildConfiguration)
  displayName: Build

- script: dotnet test GloboTicket.Gateway.Ocelot/GloboTicket.Gateway.Ocelot.csproj --no-build -c $(buildConfiguration)
  displayName: Test