trigger: none

pr:
  branches:
    include:
      - main
  paths:
    include:
      - GloboTicket.Services.Marketing/**
      - k8s/aks/aks-marketing.yaml

pool:
  name: Default

variables:
  buildConfiguration: Release

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore GloboTicket.Services.Marketing/GloboTicket.Services.Marketing.csproj
  displayName: Restore

- script: dotnet build GloboTicket.Services.Marketing/GloboTicket.Services.Marketing.csproj --no-restore -c $(buildConfiguration)
  displayName: Build

- script: dotnet test GloboTicket.Services.Marketing/GloboTicket.Services.Marketing.csproj --no-build -c $(buildConfiguration)
  displayName: Test