name: eventcatalog-$(Build.SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - GloboTicket.Services.EventCatalog/**
      - k8s/aks/aks-eventcatalog.yaml
      - k8s/aks/aks-config-eventcatalog.yaml

variables:
  tag: '$(Build.BuildId)'

stages:

# ----------------------
# BUILD STAGE
# ----------------------
- stage: Build
  displayName: Build, Scan, and Push Image
  jobs:
  - job: Build
    #pool:
    #  vmImage: 'ubuntu-latest'
    pool:
      name: Default

    steps:

    - task: Docker@2
      displayName: Build Image
      inputs:
        containerRegistry: 'sc-acr-globoticket'
        repository: 'globoticket-eventcatalog'
        command: 'build'
        Dockerfile: 'GloboTicket.Services.EventCatalog/Dockerfile'
        buildContext: '.'
        tags: |
          $(tag)

    - script: |
        docker run --rm `
          -v /var/run/docker.sock:/var/run/docker.sock `
          aquasec/trivy:0.50.0 image `
          --severity LOW,MEDIUM,HIGH,CRITICAL `
          --exit-code 0 `
          globoticket-eventcatalog:$(tag)
      displayName: "Trivy Scan (Phase 1 - Non-blocking)"
      shell: powershell

    - task: Docker@2
      displayName: Push Image
      inputs:
        containerRegistry: 'sc-acr-globoticket'
        repository: 'globoticket-eventcatalog'
        command: 'push'
        tags: |
          $(tag)

# ----------------------
# DEPLOY STAGE
# ----------------------
- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  jobs:
  - job: Deploy
    #pool:
    #  vmImage: 'ubuntu-latest'
    pool:
      name: Default

    steps:

    # Replace #{tag}# in deployment YAML
    - task: replacetokens@5
      displayName: Replace Image Tag
      inputs:
        targetFiles: 'k8s/aks/aks-eventcatalog.yaml'
        tokenPattern: 'custom'
        tokenPrefix: '#{'
        tokenSuffix: '}#'

    # Apply ConfigMap FIRST
    - task: Kubernetes@1
      displayName: Apply EventCatalog ConfigMap
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'sc-aks-globoticket'
        namespace: 'globoticket'
        command: 'apply'
        useConfigurationFile: true
        configuration: 'k8s/aks/aks-config-eventcatalog.yaml'

    # Apply Deployment + Service
    - task: Kubernetes@1
      displayName: Deploy EventCatalog
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'sc-aks-globoticket'
        namespace: 'globoticket'
        command: 'apply'
        useConfigurationFile: true
        configuration: 'k8s/aks/aks-eventcatalog.yaml'