trigger: none

pr:
  branches:
    include:
      - main
  paths:
    include:
      - GloboTicket.IDP/**
      - k8s/aks/aks-idp.yaml
      - k8s/aks/aks-idp-service.yaml
      - k8s/aks/aks-config-idp.yaml

pool:
  name: Default

variables:
  buildConfiguration: Release

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore GloboTicket.IDP/GloboTicket.IDP.csproj
  displayName: Restore

- script: dotnet build GloboTicket.IDP/GloboTicket.IDP.csproj --no-restore -c $(buildConfiguration)
  displayName: Build

- script: dotnet test GloboTicket.IDP/GloboTicket.IDP.csproj --no-build -c $(buildConfiguration)
  displayName: Test