using AutoMapper;
using GloboTicket.Gateway.WebBff.Services;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.OpenApi.Models;
using System;
using GloboTicket.Gateway.WebBff.Url;

using GloboTicket.Gateway.Shared;
using CorrelationId;
using CorrelationId.DependencyInjection;   // for AddCorrelationId extension method
using CorrelationId.HttpClient;            // if you want HttpClient propagation
using Microsoft.Extensions.Logging;

namespace GloboTicket.Gateway.WebBff
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDefaultCorrelationId(options =>
            {
                options.AddToLoggingScope = true;       // Include in log scopes
                options.EnforceHeader = false;          // Don't require clients to send one
                options.IncludeInResponse = true;       // Returns ID in response headers
                options.RequestHeader = "X-Correlation-ID";  // Default header name
                options.ResponseHeader = "X-Correlation-ID"; // Default response header name
            });

            services.AddAutoMapper(AppDomain.CurrentDomain.GetAssemblies());

            services.AddControllers();

            services.AddOptions();
            services.Configure<ServiceUrls>(Configuration.GetSection("ServiceUrls"));

            services.AddHttpClient<ICatalogService, CatalogService>(c =>
                c.BaseAddress = new Uri(Configuration["ServiceUrls:EventCatalog"]))
                .AddCorrelationIdForwarding();

            services.AddHttpClient<IBasketService, BasketService>(c =>
                c.BaseAddress = new Uri(Configuration["ServiceUrls:ShoppingBasket"]))
                .AddCorrelationIdForwarding();

            services.AddHttpClient<IDiscountService, DiscountService>(c =>
                c.BaseAddress = new Uri(Configuration["ServiceUrls:Discount"]))
                .AddCorrelationIdForwarding();

            services.AddHttpClient<IOrderService, OrderService>(c =>
                c.BaseAddress = new Uri(Configuration["ServiceUrls:Ordering"]))
                .AddCorrelationIdForwarding();

            services.AddSingleton<Settings>();

            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "GloboTicket Gateway BFF for Web API", Version = "v1" });
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseCorrelationId();

            // app.Use(async (context, next) =>
            // {
            //     var correlationId = context.TraceIdentifier;
            //     if (context.Request.Headers.TryGetValue("X-Correlation-ID", out var headerValue))
            //     {
            //         correlationId = headerValue.ToString();
            //         Console.WriteLine($"[Gateway] Incoming request with correlation ID: {correlationId}");
            //     }
            //     else
            //     {
            //         Console.WriteLine($"[Gateway] No correlation ID found. Using generated ID: {correlationId}");
            //     }

            //     await next();
            // });

            // Middleware to log the correlation ID for each incoming request
            app.Use(async (context, next) =>
            {
                // Get correlation ID from the request header, or use the one generated by the middleware
                var correlationId = context.Request.Headers.TryGetValue("X-Correlation-ID", out var headerValue)
                    ? headerValue.ToString()
                    : context.TraceIdentifier; // fallback if header missing

                // Add it to the logging scope so all logs include it
                var logger = context.RequestServices.GetRequiredService<ILogger<Startup>>();
                using (logger.BeginScope("{CorrelationId}", correlationId))
                {
                    logger.LogInformation("Incoming request {Path} with Correlation ID {CorrelationId}", context.Request.Path, correlationId);

                    await next();
                }
            });

            app.UseHttpsRedirection();

            app.UseSwagger();

            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "GloboTicket Gateway BFF for Web API V1");

            });

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }
}
